version: '3.8'

services:
  minimal-cors-server:
    build:
      context: https://github.com/MatthiasHarzer/minimal-cors-server.git
      dockerfile: Dockerfile

    environment:
      - CACHE_MODE=sqlite
      - SQLITE_FILE=/data/sqlite.db

    volumes:
      - ./data:/data

    ports:
      - "9999:8000"
    restart: always
